[buildPlans.HansCode]
family = "HansCode"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.HansCode.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-d = "standard-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-serifless"
capital-m = "hanging-serifless"
capital-q = "straight"
capital-w = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "serifless"
t = "flat-hook-short-neck2"
u = "toothless-rounded-serifless"
w = "straight-serifless"
long-s = "flat-hook-serifless"
lower-eth = "curly-bar"
lower-gamma = "casual"
lower-delta = "rounded"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight"
lower-mu = "toothed-serifless"
lower-xi = "rounded"
lower-tau = "flat-tailed"
lower-upsilon = "casual-serifless"
lower-chi = "straight-serifless"
cyrl-a = "double-storey-serifless"
cyrl-ve = "standard-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-em = "hanging-serifless"
cyrl-er = "eared-serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"
asterisk = "hex-low"
guillemet = "straight"
percent = "rings-continuous-slash"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"

[buildPlans.HansCode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.HansCode.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.HansCode.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.HansCode.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.HansCode.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"