[buildPlans.IosevkaN]
family = "Iosevka-N"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaN.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-serifless"
capital-q = "crossing-baseline"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
t = "flat-hook-short-neck2"
long-s = "flat-hook-serifless"
lower-iota = "serifed-flat-tailed"
lower-mu = "toothed-serifless"
lower-xi = "rounded"
lower-tau = "flat-tailed"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-em = "hanging-serifless"
asterisk = "hex-low"
guillemet = "straight"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"

[buildPlans.IosevkaN.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaN.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaN.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaN.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaN.slopes.Oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"